name: Tha Luvv Bugg
favicon: null
layout_spectrum: 0.7471402508672327
typography_spectrum: 0.9899133376311511
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.078779123025015
  lightness: 0.42096035764552653
  saturation: 0.9209692741278559
  rhythmicContrast: 0.01509158150292933
purpose: []
