name: Tha Luvv Bugg
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#593996'
    - '#ffffff'
    - '#000000'
    - '#949494'
    - '#f23996'
  brandStrength: 0.078779123025015
  lightness: 0.42096035764552653
  saturation: 0.625
  rhythmicContrast: 0.01509158150292933
purpose: []
